name: golangci-lint
on:
  push:
    tags:
      - v*
    branches: [ main ]
    paths:
      - '**.go'
      - .golangci.yml
      - .github/workflows/golangci-lint.yml
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - .golangci.yml
      - .github/workflows/golangci-lint.yml

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.21

      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: v1.55.2
